apiVersion: v1
kind: Pod
metadata:
  name: core-k8s 
  labels:
    role: just-an-example
    org: redhat 
    creator: gagan
spec: 
  containers:
    - name: test-pod 
      image: docker.io/busybox:latest 
      command: ['sleep','10000']
      ports: 
        - name: webapp-port 
          containerPort: 80
          protocol: TCP
